SKIPMOUNT=false

REMOVE="
/system/product/app/AnalyticsCore
/system/product/app/com.xiaomi.macro
/system/product/app/DeviceInfoQR
/system/product/app/GooglePrintRecommendationService
/system/product/app/HybridPlatform
/system/product/app/MiGameService_GameAI
/system/product/app/MIUIAccessibility
/system/product/app/MIUIgreenguard
/system/product/app/MIUISecurityInputMethod
/system/product/app/MSA
/system/product/app/SwitchAccess
/system/product/app/talkback
/system/product/data-app/BaiduIME
/system/product/data-app/iFlytekIME
/system/product/data-app/MIGalleryLockscreen
/system/product/data-app/MiRadio
/system/product/data-app/MIUIDuokanReader
/system/product/data-app/MIUIGameCenter
/system/product/data-app/MIUINewHome_Removable
/system/product/data-app/MIUIYoupin
/system/product/priv-app/MiGameCenterSDKService
/system/product/priv-app/MIUIBrowser
/system/product/priv-app/MIUIQuickSearchBox
/system/app/BasicDreams
/system/app/com.google.ar.core
/system/app/PrintRecommendationService
/system/priv-app/BuiltInPrintService
/system/priv-app/CallLogBackup
"
